vinoth=str(input("enter your text:"))
print('All Caps is')
print(vinoth.upper())
print('Small Caps is')
print(vinoth.lower())
print('Title Case is')
print(vinoth.title())
print('Start Case is')
print(vinoth.capitalize())
